# Generated by Django 4.0.5 on 2022-07-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('home_phone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_client',
            },
        ),
        migrations.CreateModel(
            name='RemedialMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RemedialClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=500)),
                ('height', models.DecimalField(decimal_places=2, max_digits=300)),
                ('martial_status', models.TextField()),
                ('children', models.IntegerField()),
                ('occupation', models.TextField()),
                ('address', models.TextField()),
                ('emergency_contact_number', models.IntegerField()),
                ('emergency_contact_name', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
            options={
                'db_table': 'core_detail_client_info',
            },
        ),
    ]
