# Generated by Django 4.0.5 on 2022-07-31 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedialclientinfo',
            name='health_insurance_number',
            field=models.DecimalField(decimal_places=0, default=0, error_messages={'invalid': 'Please enter only digits'}, max_digits=25, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedialclientinfo',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedialclientinfo',
            name='suffix',
            field=models.DecimalField(decimal_places=0, default=0, error_messages={'invalid': 'Please enter only digits'}, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='area_of_soreness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='health_care',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='medication',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='reason_of_visit',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='detail_client_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.remedialclientinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='signature',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='symptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'CHRONIC PAIN'), (2, 'HEADACHES'), (3, 'COLD / FLU / FEVER'), (4, 'DIABETES'), (5, 'HEART AILMENTS'), (6, 'KIDNEY AILMENTS'), (7, 'CANCER'), (8, 'INFECTIOUS CONDITIONS'), (9, 'HERPES'), (10, 'SHINGLES'), (11, 'ECZEMA'), (12, 'PSORIASIS'), (13, 'SKIN DISORDERS'), (14, 'AIDS'), (15, 'PHLEBITIS'), (16, 'VARICOSE VEINS'), (17, 'JOINT REPLACEMENTS'), (18, 'BLOOD CLOTS'), (19, 'TMJ SYNDROME'), (20, 'NECK OR SPINE INJURY'), (21, 'NUMBNESS'), (22, 'FATIGUE'), (23, 'DEPRESSION'), (24, 'NERVOUSNESS'), (25, 'DIZZINESS'), (26, 'ALLERGIES'), (27, 'ARTHRITIS'), (28, 'EPILEPSY'), (29, 'INSOMNIA'), (30, 'PREGNANCY'), (31, 'PMS SYNDROME'), (32, 'SLEEP DISORDERS')], default='', max_length=86),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='home_phone',
            field=models.DecimalField(blank=True, decimal_places=0, error_messages={'invalid': 'Please enter only digits'}, max_digits=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.DecimalField(blank=True, decimal_places=0, error_messages={'invalid': 'Please enter only digits'}, max_digits=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='emergency_contact_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='emergency_contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=300, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='martial_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AlterModelTable(
            name='remedialmedicalhistory',
            table='core_remedial_medical_history',
        ),
    ]
