# Generated by Django 4.0.5 on 2022-07-31 13:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='additional_comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='martial_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialmedicalhistory',
            name='health_care',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Are you currently under the care of a health care professional? If so please provide physicians name and phone number.'),
        ),
        migrations.AlterField(
            model_name='remedialmedicalhistory',
            name='medication',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Are you currently taking any medication? If so please provide the medication name.'),
        ),
        migrations.AlterField(
            model_name='remedialmedicalhistory',
            name='symptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'CHRONIC PAIN'), (2, 'HEADACHES'), (3, 'COLD / FLU / FEVER'), (4, 'DIABETES'), (5, 'HEART AILMENTS'), (6, 'KIDNEY AILMENTS'), (7, 'CANCER'), (8, 'INFECTIOUS CONDITIONS'), (9, 'HERPES'), (10, 'SHINGLES'), (11, 'ECZEMA'), (12, 'PSORIASIS'), (13, 'SKIN DISORDERS'), (14, 'AIDS'), (15, 'PHLEBITIS'), (16, 'VARICOSE VEINS'), (17, 'JOINT REPLACEMENTS'), (18, 'BLOOD CLOTS'), (19, 'TMJ SYNDROME'), (20, 'NECK OR SPINE INJURY'), (21, 'NUMBNESS'), (22, 'FATIGUE'), (23, 'DEPRESSION'), (24, 'NERVOUSNESS'), (25, 'DIZZINESS'), (26, 'ALLERGIES'), (27, 'ARTHRITIS'), (28, 'EPILEPSY'), (29, 'INSOMNIA'), (30, 'PREGNANCY'), (31, 'PMS SYNDROME'), (32, 'SLEEP DISORDERS'), (33, 'OTHER')], max_length=89),
        ),
    ]
