# Generated by Django 4.0.5 on 2022-07-28 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedialclientinfo',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='area_of_soreness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='remedial_client_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.remedialclientinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='symptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'CHRONIC PAIN'), (2, 'HEADACHES'), (3, 'COLD / FLU / FEVER')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='emergency_contact_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='emergency_contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=300, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='martial_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AlterModelTable(
            name='remedialmedicalhistory',
            table='core_remedial_medical_history',
        ),
    ]
