# Generated by Django 4.0.5 on 2022-08-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remedialclientinfo_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
