# Generated by Django 4.0.5 on 2022-08-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remedialmedicalhistory_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedialmedicalhistory',
            name='area_of_soreness',
            field=models.ImageField(blank=True, null=True, upload_to='area_of_soreness/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='remedialmedicalhistory',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipt/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='remedialmedicalhistory',
            name='signature',
            field=models.ImageField(upload_to='signature/%Y/%m/%d/'),
        ),
    ]
