# Generated by Django 4.0.5 on 2022-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_remedialmedicalhistory_area_of_soreness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedialmedicalhistory',
            name='area_of_soreness',
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='area_of_soreness_back',
            field=models.ImageField(blank=True, null=True, upload_to='area_of_soreness/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='remedialmedicalhistory',
            name='area_of_soreness_front',
            field=models.ImageField(blank=True, null=True, upload_to='area_of_soreness/%Y/%m/%d/'),
        ),
    ]
