# Generated by Django 4.0.5 on 2022-08-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_remedialmedicalhistory_area_of_soreness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedialmedicalhistory',
            name='signature',
            field=models.ImageField(blank=True, upload_to='signature/%Y/%m/%d/'),
        ),
    ]
