# Generated by Django 4.0.5 on 2022-08-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_remedialmedicalhistory_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='home_phone',
            field=models.TextField(blank=True, error_messages={'invalid': 'Please enter only digits'}, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.TextField(blank=True, error_messages={'invalid': 'Please enter only digits'}, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='health_insurance_number',
            field=models.TextField(error_messages={'invalid': 'Please enter only digits'}, max_length=25, unique=True),
        ),
    ]
