# Generated by Django 4.0.5 on 2022-09-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_client_home_phone_alter_client_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='health_insurance_number',
            field=models.TextField(error_messages={'invalid': 'Please enter only digits'}, max_length=25),
        ),
    ]
