# Generated by Django 4.0.5 on 2022-09-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_remedialclientinfo_health_insurance_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='emergency_contact_number',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
