# Generated by Django 4.0.5 on 2022-09-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_remedialclientinfo_emergency_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedialclientinfo',
            name='suffix',
            field=models.DecimalField(blank=True, decimal_places=0, error_messages={'invalid': 'Please enter only digits'}, max_digits=4, null=True),
        ),
    ]
