# Generated by Django 4.0.5 on 2024-02-15 00:29

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userprofile_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_soreness_front', models.ImageField(blank=True, null=True, upload_to='area_of_soreness/%Y/%m/%d/')),
                ('area_of_soreness_left', models.ImageField(blank=True, null=True, upload_to='area_of_soreness/%Y/%m/%d/')),
                ('area_of_soreness_right', models.ImageField(blank=True, null=True, upload_to='area_of_soreness/%Y/%m/%d/')),
                ('area_of_soreness_back', models.ImageField(blank=True, null=True, upload_to='area_of_soreness/%Y/%m/%d/')),
                ('medication', models.BooleanField()),
                ('medication_detail', models.TextField(blank=True, max_length=500, null=True, verbose_name='Are you currently taking any medication? If so please provide the medication name.')),
                ('pregnant', models.BooleanField()),
                ('pregnant_time', models.TextField()),
                ('pregnant_factor', models.TextField()),
                ('chronic_pain', models.BooleanField()),
                ('chronic_pain_detail', models.TextField()),
                ('chronic_pain_worse', models.TextField()),
                ('chronic_pain_better', models.TextField()),
                ('orthopedic_injuries', models.BooleanField()),
                ('orthopedic_injuries_detail', models.TextField()),
                ('conditions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Cancer'), (2, 'Fibromyalgia'), (3, 'Headaches/Migraines'), (4, 'Stroke'), (5, 'Arthritis'), (6, 'Heart Attack'), (7, 'Diabetes'), (8, 'Kidney Dysfunction'), (9, 'Joint Replacement(s)'), (10, 'Blood Clots'), (11, 'High/Low Blood Pressure'), (12, 'Numbness'), (13, 'Neuropathy'), (14, 'Sprains or Strains')], max_length=32, null=True)),
                ('conditions_detail', models.TextField()),
                ('professional_massage', models.BooleanField()),
                ('massage_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Relaxation'), (2, 'Therapeutic/Deep Tissue')], max_length=3, null=True)),
                ('massage_type_other', models.TextField()),
                ('pressure_preference', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Light'), (2, 'Medium'), (3, 'Deep')], max_length=5, null=True)),
                ('no_massage_area', models.BooleanField()),
                ('no_massage_area_detail', models.TextField()),
                ('reason_of_visit', models.TextField(blank=True, max_length=500, null=True)),
                ('symptoms', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'CHRONIC PAIN'), (2, 'HEADACHES'), (3, 'COLD / FLU / FEVER'), (4, 'DIABETES'), (5, 'HEART AILMENTS'), (6, 'KIDNEY AILMENTS'), (7, 'CANCER'), (8, 'INFECTIOUS CONDITIONS'), (9, 'HERPES'), (10, 'SHINGLES'), (11, 'ECZEMA'), (12, 'PSORIASIS'), (13, 'SKIN DISORDERS'), (14, 'AIDS'), (15, 'PHLEBITIS'), (16, 'VARICOSE VEINS'), (17, 'JOINT REPLACEMENTS'), (18, 'BLOOD CLOTS'), (19, 'TMJ SYNDROME'), (20, 'NECK OR SPINE INJURY'), (21, 'NUMBNESS'), (22, 'FATIGUE'), (23, 'DEPRESSION'), (24, 'NERVOUSNESS'), (25, 'DIZZINESS'), (26, 'ALLERGIES'), (27, 'ARTHRITIS'), (28, 'EPILEPSY'), (29, 'INSOMNIA'), (30, 'PREGNANCY'), (31, 'PMS SYNDROME'), (32, 'SLEEP DISORDERS'), (33, 'OTHER')], max_length=89, null=True)),
                ('health_care', models.TextField(blank=True, max_length=500, null=True, verbose_name='Are you currently under the care of a health care professional? If so please provide physicians name and phone number.')),
                ('additional_comments', models.TextField(blank=True, max_length=500, null=True)),
                ('remedial_treatment_plan', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, upload_to='signature/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipt/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'core_client_medical_history',
            },
        ),
        migrations.CreateModel(
            name='DetailClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('martial_status', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=300, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('employer', models.TextField(blank=True, null=True)),
                ('primary_physician', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.TextField(blank=True, null=True)),
                ('emergency_contact_relation', models.TextField(blank=True, max_length=50, null=True)),
                ('emergency_contact_number', models.TextField(blank=True, max_length=20, null=True)),
                ('hear_about_us', models.TextField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'core_post_code',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'core_state',
            },
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'core_suburb',
            },
        ),
        migrations.RemoveField(
            model_name='remedialmedicalhistory',
            name='detail_client_info',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='home_phone',
            new_name='phone_day',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='mobile',
            new_name='phone_night',
        ),
        migrations.AddField(
            model_name='client',
            name='health_insurance_number',
            field=models.TextField(default=0, error_messages={'invalid': 'Please enter only digits'}, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='reference_number',
            field=models.TextField(blank=True, error_messages={'invalid': 'Please enter only digits'}, max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='RemedialClientInfo',
        ),
        migrations.DeleteModel(
            name='RemedialMedicalHistory',
        ),
        migrations.AddField(
            model_name='detailclientinfo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.AddField(
            model_name='detailclientinfo',
            name='post_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postcode'),
        ),
        migrations.AddField(
            model_name='detailclientinfo',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.state'),
        ),
        migrations.AddField(
            model_name='detailclientinfo',
            name='suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.suburb'),
        ),
        migrations.AddField(
            model_name='clientmedicalhistory',
            name='detail_client_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.detailclientinfo'),
        ),
    ]
