# Generated by Django 4.0.5 on 2024-02-18 20:53

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userprofile_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('suburb', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('martial_status', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=300, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('employer', models.TextField(blank=True, null=True)),
                ('primary_physician', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.TextField(blank=True, null=True)),
                ('emergency_contact_relation', models.TextField(blank=True, max_length=50, null=True)),
                ('emergency_contact_number', models.TextField(blank=True, max_length=20, null=True)),
                ('hear_about_us', models.TextField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_client_detail_info',
            },
        ),
        migrations.CreateModel(
            name='ClientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_soreness', models.ImageField(blank=True, null=True, upload_to='area_of_soreness/%Y/%m/%d/')),
                ('medication', models.BooleanField(blank=True, null=True)),
                ('medication_detail', models.TextField(blank=True, max_length=500, null=True, verbose_name='Are you currently taking any medication? If so please provide the medication name.')),
                ('pregnant', models.BooleanField(blank=True, null=True)),
                ('pregnant_time', models.TextField(blank=True, null=True)),
                ('pregnant_factor', models.TextField(blank=True, null=True)),
                ('chronic_pain', models.BooleanField(blank=True, null=True)),
                ('chronic_pain_detail', models.TextField(blank=True, null=True)),
                ('chronic_pain_worse', models.TextField(blank=True, null=True)),
                ('chronic_pain_better', models.TextField(blank=True, null=True)),
                ('orthopedic_injuries', models.BooleanField(blank=True, null=True)),
                ('orthopedic_injuries_detail', models.TextField(blank=True, null=True)),
                ('conditions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Cancer'), ('2', 'Fibromyalgia'), ('3', 'Headaches/Migraines'), ('4', 'Stroke'), ('5', 'Arthritis'), ('6', 'Heart Attack'), ('7', 'Diabetes'), ('8', 'Kidney Dysfunction'), ('9', 'Joint Replacement(s)'), ('10', 'Blood Clots'), ('11', 'High/Low Blood Pressure'), ('12', 'Numbness'), ('13', 'Neuropathy'), ('14', 'Sprains or Strains')], max_length=32, null=True)),
                ('conditions_detail', models.TextField(blank=True, null=True)),
                ('professional_massage', models.BooleanField(blank=True, null=True)),
                ('massage_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Relaxation'), ('2', 'Therapeutic/Deep Tissue')], max_length=3, null=True)),
                ('massage_type_other', models.TextField(blank=True, null=True)),
                ('pressure_preference', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Light'), ('2', 'Medium'), ('3', 'Deep')], max_length=5, null=True)),
                ('allergies', models.BooleanField(blank=True, null=True)),
                ('allergies_detail', models.TextField(blank=True, null=True)),
                ('no_massage_area', models.BooleanField(blank=True, null=True)),
                ('no_massage_area_detail', models.TextField(blank=True, null=True)),
                ('reason_of_visit', models.TextField(blank=True, max_length=500, null=True)),
                ('symptoms', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'CHRONIC PAIN'), ('2', 'HEADACHES'), ('3', 'COLD / FLU / FEVER'), ('4', 'DIABETES'), ('5', 'HEART AILMENTS'), ('6', 'KIDNEY AILMENTS'), ('7', 'CANCER'), ('8', 'INFECTIOUS CONDITIONS'), ('9', 'HERPES'), ('10', 'SHINGLES'), ('11', 'ECZEMA'), ('12', 'PSORIASIS'), ('13', 'SKIN DISORDERS'), ('14', 'AIDS'), ('15', 'PHLEBITIS'), ('16', 'VARICOSE VEINS'), ('17', 'JOINT REPLACEMENTS'), ('18', 'BLOOD CLOTS'), ('19', 'TMJ SYNDROME'), ('20', 'NECK OR SPINE INJURY'), ('21', 'NUMBNESS'), ('22', 'FATIGUE'), ('23', 'DEPRESSION'), ('24', 'NERVOUSNESS'), ('25', 'DIZZINESS'), ('26', 'ALLERGIES'), ('27', 'ARTHRITIS'), ('28', 'EPILEPSY'), ('29', 'INSOMNIA'), ('30', 'PREGNANCY'), ('31', 'PMS SYNDROME'), ('32', 'SLEEP DISORDERS'), ('33', 'OTHER')], max_length=89, null=True)),
                ('health_care', models.TextField(blank=True, max_length=500, null=True, verbose_name='Are you currently under the care of a health care professional? If so please provide physicians name and phone number.')),
                ('additional_comments', models.TextField(blank=True, max_length=500, null=True)),
                ('remedial_treatment_plan', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, upload_to='signature/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipt/%Y/%m/%d/')),
                ('detail_client_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clientdetailinfo')),
            ],
            options={
                'db_table': 'core_client_medical_history',
            },
        ),
        migrations.RemoveField(
            model_name='remedialmedicalhistory',
            name='detail_client_info',
        ),
        migrations.RemoveField(
            model_name='client',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mobile',
        ),
        migrations.AddField(
            model_name='client',
            name='health_insurance_number',
            field=models.TextField(default=0, error_messages={'invalid': 'Please enter only digits'}, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone_day',
            field=models.TextField(blank=True, error_messages={'invalid': 'Please enter only digits'}, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_night',
            field=models.TextField(blank=True, error_messages={'invalid': 'Please enter only digits'}, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='reference_number',
            field=models.TextField(blank=True, error_messages={'invalid': 'Please enter only digits'}, max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='RemedialClientInfo',
        ),
        migrations.DeleteModel(
            name='RemedialMedicalHistory',
        ),
        migrations.AddField(
            model_name='clientdetailinfo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
    ]
