# Generated by Django 4.0.5 on 2024-02-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_clientdetailinfo_clientmedicalhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmedicalhistory',
            name='is_photo_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
