# Generated by Django 4.0.5 on 2024-02-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_clientmedicalhistory_is_photo_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmedicalhistory',
            name='form_image',
            field=models.ImageField(blank=True, null=True, upload_to='form/%Y/%m/%d/'),
        ),
    ]
