# Generated by Django 4.0.5 on 2024-02-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_clientmedicalhistory_form_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetailinfo',
            name='gender',
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='health_fund',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='DOB',
            field=models.DateField(default='0001-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='health_insurance_number',
            field=models.TextField(max_length=25),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_day',
            field=models.TextField(default=0, error_messages={'invalid': 'Please enter only digits'}, max_length=20),
            preserve_default=False,
        ),
    ]
